# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'listdel.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import qApp

from PyQt5.QtGui import QIntValidator
import pandas as pd

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Search Customer")
        Dialog.resize(240, 107)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(40, 20, 141, 16))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(150, 20, 61, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(60, 80, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(150, 80, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")



        self.onlyInt = QIntValidator()
        self.lineEdit.setValidator(self.onlyInt)
        var = self.lineEdit.text()
        self.onlyInt = QIntValidator()
        self.lineEdit.setValidator(self.onlyInt)
        self.pushButton.clicked.connect(lambda:self.listdel(var))
        self.pushButton_2.clicked.connect(self.ex)
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Enter Customer No"))
        self.pushButton.setText(_translate("Dialog", "Search"))
        self.pushButton_2.setText(_translate("Dialog", "Quit"))

    def listdel(self, a):
        data=pd.read_excel("Dummy File XYZ.xlsx")
        a = self.lineEdit.text()
        a = int(a)
        index = data.index[data['Customer No'] == a ].tolist()
        pd.DataFrame = (data.index[index].value)
        print(pd.DataFrame)


    def ex(self):
        qApp.quit()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
