# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'orderslist.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QAction,qApp
from PyQt5 import QtCore, QtGui, QtWidgets
import openpyxl, xlrd
from openpyxl import Workbook
import pathlib
import pandas as pd


class Ui_OrdersEntry(object):
    def setupUi(self, OrdersEntry):
        OrdersEntry.setObjectName("OrdersEntry")
        OrdersEntry.resize(320, 274)
        self.CusLine = QtWidgets.QLineEdit(OrdersEntry)
        self.CusLine.setGeometry(QtCore.QRect(160, 10, 113, 21))
        self.CusLine.setObjectName("CusLine")
        self.urgent_check_box = QtWidgets.QCheckBox(OrdersEntry)
        self.urgent_check_box.setGeometry(QtCore.QRect(10, 200, 121, 21))
        self.urgent_check_box.setObjectName("urgent_check_box")
        self.booking_line = QtWidgets.QLineEdit(OrdersEntry)
        self.booking_line.setGeometry(QtCore.QRect(160, 40, 113, 21))
        self.booking_line.setObjectName("booking_line")
        self.Advance_line = QtWidgets.QLineEdit(OrdersEntry)
        self.Advance_line.setGeometry(QtCore.QRect(160, 130, 113, 21))
        self.Advance_line.setObjectName("Advance_line")
        self.Quantity_line = QtWidgets.QLineEdit(OrdersEntry)
        self.Quantity_line.setGeometry(QtCore.QRect(160, 100, 113, 21))
        self.Quantity_line.setObjectName("Quantity_line")
        self.Delivery_line = QtWidgets.QLineEdit(OrdersEntry)
        self.Delivery_line.setGeometry(QtCore.QRect(160, 70, 113, 21))
        self.Delivery_line.setObjectName("Delivery_line")
        self.total_line = QtWidgets.QLineEdit(OrdersEntry)
        self.total_line.setGeometry(QtCore.QRect(160, 160, 113, 21))
        self.total_line.setObjectName("total_line")
        self.CusNo = QtWidgets.QLabel(OrdersEntry)
        self.CusNo.setGeometry(QtCore.QRect(10, 10, 141, 20))
        self.CusNo.setObjectName("CusNo")
        self.label_2 = QtWidgets.QLabel(OrdersEntry)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 141, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(OrdersEntry)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 141, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(OrdersEntry)
        self.label_4.setGeometry(QtCore.QRect(10, 100, 141, 20))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(OrdersEntry)
        self.label_5.setGeometry(QtCore.QRect(10, 130, 141, 20))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(OrdersEntry)
        self.label_6.setGeometry(QtCore.QRect(10, 160, 141, 20))
        self.label_6.setObjectName("label_6")
        self.pushButton = QtWidgets.QPushButton(OrdersEntry)
        self.pushButton.setGeometry(QtCore.QRect(140, 240, 75, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(OrdersEntry)
        self.pushButton_2.setGeometry(QtCore.QRect(240, 240, 75, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton.clicked.connect(self.append)
        self.retranslateUi(OrdersEntry)
        self.pushButton_2.clicked.connect(self.ex)
        QtCore.QMetaObject.connectSlotsByName(OrdersEntry)
        # file = pathlib.Path("Dummy File XYZ.xlsx")
        df = pd.read_csv("Dummy File XYZ 11.csv")
        # if file.exists():
        #     pass
        # else:
        #     file = Workbook()
        #     sheet["A1"] = " Customer Name "
        #     sheet["B1"] = " Booking "
        #     sheet["C1"] = " Delivery "
        #     sheet["D1"] = " Quantity "
        #     sheet["E1"] = " Advanced "
        #     sheet["F1"] = " Total Rs "
        #     sheet["F1"] = " Urgent "
        #     file.save("Dummy File XYZ.xlsx")
        #     file.to_cs



    def append(self):
        y = self.CusLine.text()
        z = self.booking_line.text()
        z1 = self.Delivery_line.text()
        z2 = self.Quantity_line.text()
        z3 = self.Advance_line.text()
        z4 = self.total_line.text()

        # file = openpyxl.load_workbook("Dummy File XYZ.xlsx")
        # sheet = file.active
        # sheet.cell(column=1, row=sheet.max_row+1, value=y)
        # sheet.cell(column=2, row=sheet.max_row, value=z)
        # sheet.cell(column=3, row=sheet.max_row, value=z1)
        # sheet.cell(column=4, row=sheet.max_row, value=z2)
        # sheet.cell(column=5, row=sheet.max_row, value=z3)
        # sheet.cell(column=6, row=sheet.max_row, value=z4)

        df = pd.read_csv("Dummy File XYZ 11.csv")

        # if self.urgent_check_box.isChecked() ==True:
        #     sheet.cell(column=7, row=sheet.max_row, value="Yes")
        # else:
        #     sheet.cell(column=7, row=sheet.max_row, value="No")

        x = self.urgent_check_box.isChecked()
        urgent = "No"
        if x:
            urgent = "Yes"
        addData = ({
                    "Customer No":y,
                    "Booking": z,
                    "Delivery":z1,
                    "Quantity":z2,
                    "Advance":z3,
                    "Total Rs":z4,
                    "Urgent":urgent
        })

        df = df.append(addData,ignore_index=True)
        df = df.to_csv('Dummy File XYZ 11.csv', mode='a', header=False)
        # file.save("Dummy File XYZ.xlsx")

    def ex(self):
        qApp.quit()


    def retranslateUi(self, OrdersEntry):
        _translate = QtCore.QCoreApplication.translate
        OrdersEntry.setWindowTitle(_translate("OrdersEntry", "Form"))
        self.urgent_check_box.setText(_translate("OrdersEntry", "Urgent"))
        self.CusNo.setText(_translate("OrdersEntry", "Customer No"))
        self.label_2.setText(_translate("OrdersEntry", "Booking"))
        self.label_3.setText(_translate("OrdersEntry", "Delivery"))
        self.label_4.setText(_translate("OrdersEntry", "Quantity"))
        self.label_5.setText(_translate("OrdersEntry", "Advance"))
        self.label_6.setText(_translate("OrdersEntry", "Total Rs"))
        self.pushButton.setText(_translate("OrdersEntry", "Append"))
        self.pushButton_2.setText(_translate("OrdersEntry", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OrdersEntry = QtWidgets.QWidget()
    ui = Ui_OrdersEntry()
    ui.setupUi(OrdersEntry)
    OrdersEntry.show()
    sys.exit(app.exec_())
